// Mapeamento best-effort da taxonomia própria do Pluggy para os slugs do
// MoneyLens — usado como sinal antes de acionar o LLM. Não precisa ser
// exaustivo: o que não bater aqui simplesmente segue pro fallback do Gemini.
export const PLUGGY_CATEGORY_MAP: Record<string, string> = {
  'Music streaming': 'assinaturas',
  'Video streaming': 'assinaturas',
  'Telecommunications': 'moradia',
  'Transfer - Bank Slip': 'transferencias',
  'Bank Slip': 'transferencias',
  'Transfers': 'transferencias',
  'Salary': 'receita',
  'Income': 'receita',
  'Restaurants and Bars': 'alimentacao',
  'Groceries': 'alimentacao',
  'Supermarkets': 'alimentacao',
  'Food Delivery': 'alimentacao',
  'Uber and Taxi': 'transporte',
  'Fuel': 'transporte',
  'Parking': 'transporte',
  'Public Transportation': 'transporte',
  'Pharmacy': 'saude',
  'Health': 'saude',
  'Gym and Fitness': 'saude',
  'Electronics': 'compras',
  'Clothing': 'compras',
  'Online Shopping': 'compras',
  'Rent': 'moradia',
  'Utilities': 'moradia',
  'Electricity': 'moradia',
  'Water': 'moradia',
  'Entertainment': 'lazer',
  'Movies': 'lazer',
  'Fees': 'taxas',
  'Interest': 'taxas',
  'Loans and Financing': 'taxas',
  'Taxes': 'taxas',
};
